apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: mybestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybestapp
  template:
    metadata:
      labels:
        app: mybestapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
